"""parte 5: banco de problemas e submissoes

Revision ID: 015859f4458c
Revises: e2413d62ffd7
Create Date: 2026-08-06 13:04:57.644710

"""
import uuid
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '015859f4458c'
down_revision: str | None = 'e2413d62ffd7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags_problema',
    sa.Column('categoria', sa.Enum('TEMA', 'RACIOCINIO', name='categoria_tag'), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_problema_codigo'), 'tags_problema', ['codigo'], unique=True)
    op.create_table('problemas',
    sa.Column('instituicao_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('enunciado', sa.Text(), nullable=False),
    sa.Column('linguagem', sa.String(length=30), nullable=False),
    sa.Column('nivel_dificuldade', sa.Enum('FACIL', 'MEDIO', 'DIFICIL', name='nivel_dificuldade'), nullable=False),
    sa.Column('criado_por_id', sa.UUID(), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicoes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problemas_instituicao_id'), 'problemas', ['instituicao_id'], unique=False)
    op.create_table('casos_teste',
    sa.Column('problema_id', sa.UUID(), nullable=False),
    sa.Column('entrada', sa.Text(), nullable=False),
    sa.Column('saida_esperada', sa.Text(), nullable=False),
    sa.Column('publico', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ordem', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['problema_id'], ['problemas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_casos_teste_problema_id'), 'casos_teste', ['problema_id'], unique=False)
    op.create_table('problema_tags',
    sa.Column('problema_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['problema_id'], ['problemas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags_problema.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('problema_id', 'tag_id')
    )
    op.create_table('problema_turmas',
    sa.Column('problema_id', sa.UUID(), nullable=False),
    sa.Column('turma_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['problema_id'], ['problemas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('problema_id', 'turma_id')
    )
    op.create_table('submissoes',
    sa.Column('problema_id', sa.UUID(), nullable=False),
    sa.Column('aluno_id', sa.UUID(), nullable=False),
    sa.Column('codigo_fonte', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('ACEITO', 'REPROVADO', 'ERRO_EXECUCAO', 'TEMPO_EXCEDIDO', 'ERRO_INTERNO', name='status_submissao'), nullable=False),
    sa.Column('tempo_execucao_ms', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['problema_id'], ['problemas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissoes_aluno_id'), 'submissoes', ['aluno_id'], unique=False)
    op.create_index(op.f('ix_submissoes_problema_id'), 'submissoes', ['problema_id'], unique=False)
    op.create_table('submissao_resultados',
    sa.Column('submissao_id', sa.UUID(), nullable=False),
    sa.Column('caso_teste_id', sa.UUID(), nullable=False),
    sa.Column('passou', sa.Boolean(), nullable=False),
    sa.Column('saida_obtida', sa.Text(), nullable=False),
    sa.Column('erro_sanitizado', sa.Text(), nullable=True),
    sa.Column('tempo_execucao_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['caso_teste_id'], ['casos_teste.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submissao_id'], ['submissoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissao_resultados_submissao_id'), 'submissao_resultados', ['submissao_id'], unique=False)
    # ### end Alembic commands ###

    # --- Seed do vocabulario inicial de tags de problema ------------------
    # Extensivel: novas tags podem ser adicionadas depois via INSERT, sem
    # nova migration de schema (mesmo padrao de condicoes_neurodivergencia).
    tags_iniciais = [
        # (categoria, codigo, nome)
        ('tema', 'loops', 'Lacos de repeticao'),
        ('tema', 'condicionais', 'Estruturas condicionais'),
        ('tema', 'recursao', 'Recursao'),
        ('tema', 'strings', 'Manipulacao de texto'),
        ('tema', 'listas', 'Listas e colecoes'),
        ('tema', 'funcoes', 'Funcoes'),
        (
            'raciocinio', 'logica_sequencial',
            'Raciocinio logico sequencial (passo a passo)',
        ),
        ('raciocinio', 'abstracao', 'Capacidade de abstracao'),
        ('raciocinio', 'memoria_trabalho', 'Memoria de trabalho (varias variaveis simultaneas)'),
        ('raciocinio', 'decomposicao', 'Decomposicao do problema em subproblemas'),
        ('raciocinio', 'padroes', 'Reconhecimento de padroes'),
    ]
    tags_table = sa.table(
        'tags_problema',
        sa.column('id', sa.UUID()),
        sa.column('categoria', sa.Enum('TEMA', 'RACIOCINIO', name='categoria_tag')),
        sa.column('codigo', sa.String()),
        sa.column('nome', sa.String()),
        sa.column('ativo', sa.Boolean()),
    )
    op.bulk_insert(
        tags_table,
        [
            {
                'id': uuid.uuid4(),
                'categoria': categoria.upper(),
                'codigo': codigo,
                'nome': nome,
                'ativo': True,
            }
            for categoria, codigo, nome in tags_iniciais
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissao_resultados_submissao_id'), table_name='submissao_resultados')
    op.drop_table('submissao_resultados')
    op.drop_index(op.f('ix_submissoes_problema_id'), table_name='submissoes')
    op.drop_index(op.f('ix_submissoes_aluno_id'), table_name='submissoes')
    op.drop_table('submissoes')
    op.drop_table('problema_turmas')
    op.drop_table('problema_tags')
    op.drop_index(op.f('ix_casos_teste_problema_id'), table_name='casos_teste')
    op.drop_table('casos_teste')
    op.drop_index(op.f('ix_problemas_instituicao_id'), table_name='problemas')
    op.drop_table('problemas')
    op.drop_index(op.f('ix_tags_problema_codigo'), table_name='tags_problema')
    op.drop_table('tags_problema')
    # ### end Alembic commands ###
