"""parte 3: instituicoes, perfis de adaptacao

Revision ID: 1316bb540ab8
Revises: d5b8894b573a
Create Date: 2026-08-06 10:54:11.483302

"""
import uuid
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1316bb540ab8'
down_revision: str | None = 'd5b8894b573a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condicoes_neurodivergencia',
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_condicoes_neurodivergencia_codigo'), 'condicoes_neurodivergencia', ['codigo'], unique=True)
    op.create_table('instituicoes',
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instituicoes_codigo'), 'instituicoes', ['codigo'], unique=True)
    op.create_table('perfis_aluno',
    sa.Column('aluno_id', sa.UUID(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_por_id', sa.UUID(), nullable=False),
    sa.Column('consentimento_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consentimento_versao', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aluno_id', 'versao', name='uq_perfil_aluno_versao')
    )
    op.create_index(op.f('ix_perfis_aluno_aluno_id'), 'perfis_aluno', ['aluno_id'], unique=False)
    op.create_table('perfis_big_five',
    sa.Column('aluno_id', sa.UUID(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('score_abertura', sa.Float(), nullable=False),
    sa.Column('score_conscienciosidade', sa.Float(), nullable=False),
    sa.Column('score_extroversao', sa.Float(), nullable=False),
    sa.Column('score_amabilidade', sa.Float(), nullable=False),
    sa.Column('score_neuroticismo', sa.Float(), nullable=False),
    sa.Column('respostas_brutas', sa.JSON(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aluno_id', 'versao', name='uq_perfil_big_five_versao')
    )
    op.create_index(op.f('ix_perfis_big_five_aluno_id'), 'perfis_big_five', ['aluno_id'], unique=False)
    op.create_table('preferencias_acessibilidade',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('fonte_legivel', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('alto_contraste', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('tempo_extra_percentual', sa.Integer(), server_default='0', nullable=False),
    sa.Column('leitura_voz_alta', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('reducao_estimulos', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('tamanho_fonte', sa.String(length=10), server_default='medio', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preferencias_acessibilidade_usuario_id'), 'preferencias_acessibilidade', ['usuario_id'], unique=True)
    op.create_table('perfil_aluno_condicoes',
    sa.Column('perfil_aluno_id', sa.UUID(), nullable=False),
    sa.Column('condicao_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['condicao_id'], ['condicoes_neurodivergencia.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['perfil_aluno_id'], ['perfis_aluno.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('perfil_aluno_id', 'condicao_id')
    )
    op.add_column('usuarios', sa.Column('instituicao_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_usuarios_instituicao_id'), 'usuarios', ['instituicao_id'], unique=False)
    op.create_foreign_key(
        'fk_usuarios_instituicao_id_instituicoes',
        'usuarios', 'instituicoes', ['instituicao_id'], ['id'], ondelete='RESTRICT',
    )
    # ### end Alembic commands ###

    # --- Backfill seguro (nao gerado pelo autogenerate) ------------------
    # Usuarios criados antes desta migration (ex: dados da Parte 2) nao tem
    # instituicao_id. Em vez de apaga-los ou deixar a coluna nullable para
    # sempre, criamos uma instituicao padrao e vinculamos qualquer usuario
    # orfao a ela antes de tornar a coluna obrigatoria. Passo idempotente:
    # se nenhum usuario estiver sem instituicao, nada e inserido.
    connection = op.get_bind()
    metadata = sa.MetaData()
    instituicoes = sa.Table('instituicoes', metadata, autoload_with=connection)
    usuarios = sa.Table('usuarios', metadata, autoload_with=connection)

    existe_orfao = connection.execute(
        sa.select(usuarios.c.id).where(usuarios.c.instituicao_id.is_(None)).limit(1)
    ).first()

    if existe_orfao is not None:
        instituicao_padrao_id = uuid.uuid4()
        connection.execute(
            instituicoes.insert().values(
                id=instituicao_padrao_id,
                nome='Instituicao Padrao (migracao automatica)',
                codigo='MIGRACAO-PADRAO',
                ativo=True,
            )
        )
        connection.execute(
            usuarios.update()
            .where(usuarios.c.instituicao_id.is_(None))
            .values(instituicao_id=instituicao_padrao_id)
        )

    op.alter_column('usuarios', 'instituicao_id', nullable=False)

    # --- Seed do vocabulario inicial de condicoes de neurodivergencia ----
    # Lista extensivel: novas condicoes podem ser adicionadas depois via
    # INSERT direto, sem nova migration de schema.
    condicoes_iniciais = [
        ('tdah', 'TDAH', 'Transtorno de Deficit de Atencao e Hiperatividade'),
        ('tea', 'TEA', 'Transtorno do Espectro Autista'),
        ('dislexia', 'Dislexia', 'Dificuldade especifica de leitura'),
        ('discalculia', 'Discalculia', 'Dificuldade especifica com numeros e calculo'),
        ('disgrafia', 'Disgrafia', 'Dificuldade especifica de escrita'),
        (
            'processamento_sensorial',
            'Transtorno de Processamento Sensorial',
            'Dificuldade em processar e integrar estimulos sensoriais',
        ),
    ]
    condicoes_table = sa.table(
        'condicoes_neurodivergencia',
        sa.column('id', sa.UUID()),
        sa.column('codigo', sa.String()),
        sa.column('nome', sa.String()),
        sa.column('descricao', sa.Text()),
        sa.column('ativo', sa.Boolean()),
    )
    op.bulk_insert(
        condicoes_table,
        [
            {
                'id': uuid.uuid4(),
                'codigo': codigo,
                'nome': nome,
                'descricao': descricao,
                'ativo': True,
            }
            for codigo, nome, descricao in condicoes_iniciais
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_usuarios_instituicao_id_instituicoes', 'usuarios', type_='foreignkey')
    op.drop_index(op.f('ix_usuarios_instituicao_id'), table_name='usuarios')
    op.drop_column('usuarios', 'instituicao_id')
    op.drop_table('perfil_aluno_condicoes')
    op.drop_index(op.f('ix_preferencias_acessibilidade_usuario_id'), table_name='preferencias_acessibilidade')
    op.drop_table('preferencias_acessibilidade')
    op.drop_index(op.f('ix_perfis_big_five_aluno_id'), table_name='perfis_big_five')
    op.drop_table('perfis_big_five')
    op.drop_index(op.f('ix_perfis_aluno_aluno_id'), table_name='perfis_aluno')
    op.drop_table('perfis_aluno')
    op.drop_index(op.f('ix_instituicoes_codigo'), table_name='instituicoes')
    op.drop_table('instituicoes')
    op.drop_index(op.f('ix_condicoes_neurodivergencia_codigo'), table_name='condicoes_neurodivergencia')
    op.drop_table('condicoes_neurodivergencia')
    # ### end Alembic commands ###
