"""parte 6 motor de ia adaptativa - dicas

Revision ID: d639cf9ceefd
Revises: 015859f4458c
Create Date: 2026-08-06 13:34:02.369502

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd639cf9ceefd'
down_revision: str | None = '015859f4458c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dicas',
    sa.Column('problema_id', sa.UUID(), nullable=False),
    sa.Column('aluno_id', sa.UUID(), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('adaptacoes_aplicadas', sa.JSON(), nullable=False),
    sa.Column('resolvida_apos', sa.Boolean(), nullable=False),
    sa.Column('tempo_ate_resolver_ms', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['problema_id'], ['problemas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dicas_aluno_id'), 'dicas', ['aluno_id'], unique=False)
    op.create_index(op.f('ix_dicas_problema_id'), 'dicas', ['problema_id'], unique=False)
    # Consulta mais frequente do servico (app/services/dica_service.py):
    # "qual o maior nivel ja dado para este aluno+problema" e "quais dicas
    # ainda aguardam resultado" - ambas filtram por este par.
    op.create_index(
        'ix_dicas_problema_aluno', 'dicas', ['problema_id', 'aluno_id'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dicas_problema_aluno', table_name='dicas')
    op.drop_index(op.f('ix_dicas_problema_id'), table_name='dicas')
    op.drop_index(op.f('ix_dicas_aluno_id'), table_name='dicas')
    op.drop_table('dicas')
    # ### end Alembic commands ###
