"""parte 4: turmas e matriculas

Revision ID: e2413d62ffd7
Revises: 1316bb540ab8
Create Date: 2026-08-06 12:39:57.835914

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e2413d62ffd7'
down_revision: str | None = '1316bb540ab8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turmas',
    sa.Column('instituicao_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('periodo', sa.String(length=50), nullable=False),
    sa.Column('professor_responsavel_id', sa.UUID(), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicoes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['professor_responsavel_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turmas_instituicao_id'), 'turmas', ['instituicao_id'], unique=False)
    op.create_index(op.f('ix_turmas_professor_responsavel_id'), 'turmas', ['professor_responsavel_id'], unique=False)
    op.create_table('matriculas',
    sa.Column('turma_id', sa.UUID(), nullable=False),
    sa.Column('aluno_id', sa.UUID(), nullable=False),
    sa.Column('matriculado_por_id', sa.UUID(), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('matriculado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('desmatriculado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matriculado_por_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matriculas_aluno_id'), 'matriculas', ['aluno_id'], unique=False)
    op.create_index(op.f('ix_matriculas_turma_id'), 'matriculas', ['turma_id'], unique=False)
    op.create_table('turma_professores',
    sa.Column('turma_id', sa.UUID(), nullable=False),
    sa.Column('professor_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['professor_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('turma_id', 'professor_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turma_professores')
    op.drop_index(op.f('ix_matriculas_turma_id'), table_name='matriculas')
    op.drop_index(op.f('ix_matriculas_aluno_id'), table_name='matriculas')
    op.drop_table('matriculas')
    op.drop_index(op.f('ix_turmas_professor_responsavel_id'), table_name='turmas')
    op.drop_index(op.f('ix_turmas_instituicao_id'), table_name='turmas')
    op.drop_table('turmas')
    # ### end Alembic commands ###
